import React from 'react';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

interface TermsViewProps {
  onBack: () => void;
  onOpenDashboard: () => void;
  onOpenPrivacy: () => void;
}

export const TermsView: React.FC<TermsViewProps> = ({ onBack, onOpenDashboard, onOpenPrivacy }) => {
  return (
    <div style={{
      minHeight: '100vh',
      backgroundColor: '#ffffff',
      color: '#09090b',
      fontFamily: "'Inter', sans-serif",
      paddingBottom: '60px'
    }}>
      {/* Header */}
      <header style={{
        position: 'sticky',
        top: 0,
        zIndex: 50,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        backdropFilter: 'blur(12px)',
        borderBottom: '1px solid #e4e4e7',
        padding: '16px 32px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <button
            onClick={onBack}
            className="btn-outline"
            style={{ padding: '6px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px', borderRadius: '9999px', border: '1px solid #e4e4e7', background: '#ffffff', cursor: 'pointer' }}
            aria-label="Go back"
          >
            <ArrowLeft size={14} /> Back
          </button>
          <span style={{ fontWeight: 700, fontSize: '18px', letterSpacing: '-0.02em' }}>Terms of Service</span>
        </div>
        <button onClick={onOpenDashboard} className="btn-black" style={{ padding: '8px 18px', fontSize: '13px', fontWeight: 600 }}>
          Open Dashboard →
        </button>
      </header>

      {/* Content */}
      <main style={{ maxWidth: '800px', margin: '0 auto', padding: '48px 24px' }} role="main" aria-label="Terms of Service">
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: '#f4f4f6', padding: '6px 16px', borderRadius: '9999px', fontSize: '12px', fontWeight: 600, color: '#333', marginBottom: '20px' }}>
          <ShieldCheck size={16} color="#16a34a" />
          <span>Fair & Transparent Usage</span>
        </div>

        <h1 style={{ fontSize: '32px', fontWeight: 300, letterSpacing: '-0.02em', marginBottom: '8px' }}>Terms of Service</h1>
        <p style={{ fontSize: '13px', color: '#888', marginBottom: '36px' }}>Last updated: August 2026</p>

        <article style={{ fontSize: '15px', lineHeight: 1.8, color: '#334155' }}>
          <Section title="1. Acceptance of Terms">
            By accessing or using FairMatch AI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.
          </Section>

          <Section title="2. Description of Service">
            FairMatch AI provides job-specific resume analysis, skill evidence matching, and actionable career feedback. The Platform is designed as an advisory tool to help job candidates understand resume alignment against job descriptions.
          </Section>

          <Section title="3. AI Content & Advisory Disclaimer">
            <p>
              The insights, strengths, missing requirements, and recommendations generated by FairMatch AI are created using automated language processing and skill taxonomy matching.
            </p>
            <ul style={{ paddingLeft: '20px', margin: '8px 0' }}>
              <li>Analysis results are <strong>advisory only</strong> and do not guarantee interview invites or job offers.</li>
              <li>FairMatch AI does not make employment decisions or act as an employment agency.</li>
              <li>Users remain responsible for reviewing and customizing their resumes accurately.</li>
            </ul>
          </Section>

          <Section title="4. User Conduct & Responsibilities">
            <ul style={{ paddingLeft: '20px', margin: '8px 0' }}>
              <li>You agree to submit only resumes and job descriptions you have the right to provide.</li>
              <li>You agree not to upload malicious files, scripts, or offensive content.</li>
              <li>You agree not to attempt to reverse engineer, disrupt, or exploit the Platform's APIs.</li>
            </ul>
          </Section>

          <Section title="5. Intellectual Property">
            All design systems, UI components, platform code, and branding associated with FairMatch AI are the property of the platform operators. Your resume content remains your intellectual property.
          </Section>

          <Section title="6. Limitation of Liability">
            FairMatch AI and its developers shall not be liable for any indirect, incidental, or consequential damages resulting from your use of or inability to use the Platform, or any employment decisions made by third parties.
          </Section>

          <Section title="7. Modifications to Terms">
            We reserve the right to update these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated Terms.
          </Section>

          <Section title="8. Contact Information">
            <p>
              For questions regarding these Terms, please contact us via the contact channels provided on the website.
            </p>
          </Section>

          <div style={{ marginTop: '24px', paddingTop: '16px', borderTop: '1px solid #e4e4e7', fontSize: '13px', color: '#888' }}>
            <button
              onClick={onOpenPrivacy}
              style={{ background: 'none', border: 'none', color: '#2563eb', cursor: 'pointer', fontSize: '13px', fontWeight: 500, padding: 0 }}
            >
              View Privacy Policy →
            </button>
          </div>
        </article>
      </main>
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <section style={{ marginBottom: '28px' }}>
    <h2 style={{ fontSize: '18px', fontWeight: 600, color: '#09090b', marginBottom: '8px' }}>{title}</h2>
    <div>{children}</div>
  </section>
);
